In [ ]:
import numpy as np

custo_cilindro = np.array([50, 60, 70])
custo_esfera = np.array([30, 40, 50])

print("1) Considerando o exemplo do empresário que pretende estabelecer uma empresa especializada em montar um produto composto de uma esfera e um cilindro. Considere a variável aleatória T como sendo a variável “custo de recuperação de cada composto produzido (cilindro+esfera)”, e determine os valores assumidos por T:")

T_valores = np.empty((len(custo_cilindro), len(custo_esfera)))

for i in range(len(custo_cilindro)):
    for j in range(len(custo_esfera)):
        T_valores[i, j] = custo_cilindro[i] + custo_esfera[j]
print("Valores de T:")
print(T_valores)

1) Considerando o exemplo do empresário que pretende estabelecer uma empresa especializada em montar um produto composto de uma esfera e um cilindro. Considere a variável aleatória T como sendo a variável “custo de recuperação de cada composto produzido (cilindro+esfera)”, e determine os valores assumidos por T:
Valores de T:
[[ 80.  90. 100.]
 [ 90. 100. 110.]
 [100. 110. 120.]]


In [ ]:
import numpy as np
from itertools import combinations

urna = ['B', 'B', 'V', 'V', 'V']

print("2) Imagine urna contendo duas bolas brancas (B) e três bolas vermelhas (V). Em um cenário onde são sorteadas duas bolas ao acaso, sem reposição da bola sorteada de volta na urna (escolhe-se a primeira bola, verifica-se a cor e não se devolve à urna; mistura-se as bolas restantes e retira-se a segunda. Considere a variável aleatória H  'número de bolas vermelhas obtidas nas duas extrações', quais os valores que podem ser assumidos por H?")

comb = list(combinations(urna, 2))

count_H = {0: 0, 1: 0, 2: 0}

for c in comb:
    num_vermelhas = c.count('V')
    count_H[num_vermelhas] += 1

print("Valores de H:")
for h, count in count_H.items():
    print(f"[H é {h}, têm {count} ocorrências]")

2) Imagine urna contendo duas bolas brancas (B) e três bolas vermelhas (V). Em um cenário onde são sorteadas duas bolas ao acaso, sem reposição da bola sorteada de volta na urna (escolhe-se a primeira bola, verifica-se a cor e não se devolve à urna; mistura-se as bolas restantes e retira-se a segunda. Considere a variável aleatória H  'número de bolas vermelhas obtidas nas duas extrações', quais os valores que podem ser assumidos por H?
Valores de H:
[H é 0, têm 1 ocorrências]
[H é 1, têm 6 ocorrências]
[H é 2, têm 3 ocorrências]


In [ ]:
resultados_possiveis = ['Cara', 'Coroa']

valores_W = set()

for resultado1 in resultados_possiveis:
    for resultado2 in resultados_possiveis:
        resultado_concatenado = resultado1 + resultado2
        num_caras = resultado_concatenado.count('Cara')
        valores_W.add(num_caras)

valores_W_ordenados = sorted(valores_W)

print("3) Considere o lançamento de uma moeda duas vezes. Define-se a variável aleatória W 'número de caras obtidas nos dois lançamentos'. Quais os valores assumidos pela variável aleatória W?")

print("Valores de W:")
print(valores_W_ordenados)

3) Considere o lançamento de uma moeda duas vezes. Define-se a variável aleatória W 'número de caras obtidas nos dois lançamentos'. Quais os valores assumidos pela variável aleatória W?
Valores de W:
[0, 1, 2]
